AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  UserCache: false
  TargetRubyVersion: 2.3
  DisplayStyleGuide: true
Rails:
  Enabled: true
Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false
